### ISSUE TITLE
@geolonia/normalize-japanese-addressesと違う結果

### ISSUE THREAD

**Issue by TylerLee0516** [Taka710/normalize-japanese-addresses-py#8]
`北海道札幌市中央区宮の森４条１０丁目`を正規化した結果は
`{'pref': '北海道', 'city': '札幌市中央区', 'town': '宮の森', 'address': '4条10', 'level': 3, 'lat': 43.044885, 'long': 141.287113}`
ですが、@geolonia/normalize-japanese-addressesで実行した結果は
`{pref: '北海道', city: '札幌市中央区', town: '宮の森四条十丁目', addr: '', level: 3`
です。

**Comment by Taka710** [comment]
v0.0.9では解決していると思います
テストにて動作確認済みです
