### ISSUE TITLE
茨城県行方市をnormalizeするとUnboundLocalErrorが発生する

### ISSUE THREAD

**Issue by nb-yazawa** [Taka710/normalize-japanese-addresses-py#9]
以下を実行しますとエラーが発生します
from normalize_japanese_addresses import normalize
print(normalize("茨城県行方市"))

**Comment by nb-yazawa** [comment]
以下を実行しますとエラーが発生します
from normalize_japanese_addresses import normalize
print(normalize("千葉県茂原市"))

**Comment by Taka710** [comment]
v0.0.9で修正しました
